### ISSUE TITLE
Crear Usuario nuevo

### ISSUE THREAD

**Issue by luishark2** [luishark2/proyecto1#1]
Crear la vista de un usuario nuevo, donde pida nombre, apellido, correo y contraseña,

**Comment by jcamarenaj** [comment]
profe se creo la vista de Usuario y se realizaron las pruebas 😎

**Comment by luishark2** [comment]
Corregir el error de que no guarda cuando se presiona el botón de guardar

**Comment by jcamarenaj** [comment]
se corrigió  el botón
